name: Test Action

on:
  workflow_dispatch:
    inputs:
      linear_issue_id:
        description: 'Linear Issue ID'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Claude CLI
        run: |
          # Install the Claude CLI
          curl -sL "https://anthropic.com/claude-cli/install" | bash -s -- -b ~/.local/bin
          
          # Add to PATH for this job
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
          # Configure Claude CLI with API key
          mkdir -p ~/.config/anthropic
          cat > ~/.config/anthropic/config.json << EOF
          {
            "api_key": "${{ secrets.CLAUDE_API_KEY }}"
          }
          EOF
          
          # Set permissions
          chmod 600 ~/.config/anthropic/config.json
          
          # Verify installation
          claude --version
          
          # Check configuration
          echo "Checking Claude configuration..."
          claude -p "hello" || echo "Claude configuration check failed but continuing..."
      
      - name: Run Linear to PR Action
        uses: ./
        with:
          linear_api_key: ${{ secrets.LINEAR_API_KEY }}
          linear_issue_id: ${{ github.event.inputs.linear_issue_id }}
          github_token: ${{ secrets.GITHUB_TOKEN }}